version: '2'

services: 
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginxproxy_nextcloud/certs:/etc/nginx/certs:ro
            - /etc/nginx/vhost.d 
            - /usr/share/nginx/html
            - ./nginxproxy_nextcloud/nginx.conf:/etc/nginx/nginx.conf

    letsencrypt:
        image:  jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes: 
            - ./nginxproxy_nextcloud/certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from: 
            - nginx-proxy:rw


    db:
        image: postgres
        restart: always
        hostname: 'db'
        volumes:
        - ./db:/var/lib/postgresql/data
        environment:
        - POSTGRES_PASSWORD=
        - POSTGRES_DB=nextcloud
        - POSTGRES_USER=nextcloud

    app:
        image: nextcloud
        restart: always
        volumes:
        - ./nextcloud:/var/www/html
        ports:
        - "80"
        environment:
        - POSTGRES_PASSWORD=
        - POSTGRES_DB=nextcloud
        - POSTGRES_USER=nextcloud
        - POSTGRES_HOST=db
        - VIRTUAL_HOST=
        - LETSENCRYPT_HOST=
        - LETSENCRYPT_EMAIL= 
        depends_on: 
            - db

